# emailsenderconfig.yaml
apiVersion: example.com/v1
kind: EmailSenderConfig
metadata:
  name: my-email-config
  namespace: email-operator
spec:|
  provider: mailersend  # It can be 'mailersend' o 'mailgun'
  apiTokenSecretRef: my-email-secret
  senderEmail: sender@example.com

