# config/helm/email-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-operator
  namespace: email-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-operator
  template:
    metadata:
      labels:
        app: email-operator
    spec:
      serviceAccountName: email-operator
      containers:
        - name: email-operator
          image: email-operator:latest
          ports:
            - containerPort: 8080
              name: metrics
          resources:
            limits:
              cpu: 0.8
              memory: 256Mi
            requests:
              cpu: 0.4
              memory: 128Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: email-operator
  namespace: email-operator

