# config/helm/email-operator/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: email-operator
  name: email-operator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["example.com"]
    resources: ["emails", "emailsenderconfigs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: email-operator
  namespace: email-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: email-operator
subjects:
  - kind: ServiceAccount
    name: email-operator
    namespace: email-operator

